### ISSUE TITLE
Non-existant plugin added

### ISSUE THREAD

**Issue by samuelallan72** [canonical/snap-tempest-automation#14]
See https://github.com/canonical/snap-tempest/pull/195#pullrequestreview-2150296438

It tried adding a new plugin to the snapcraft.yaml.  This plugin existed in an earlier revision of stable/ussuri branch, but did not exist at the time when the PR to add it was raised.

**Comment by gabrielcocenza** [comment]
My two cents is that if we don't want to be added we should include at the [excluded-plugins.txt](https://github.com/canonical/snap-tempest-automation/blob/main/excluded-plugins.txt). If we don't do that, probably it will go to the [ussuri](https://opendev.org/openstack/releases/src/branch/master/deliverables/ussuri) release page and then it will find congress
